config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ads
  root 'ads#index'
  get 'myAd',to:'ads#myAd'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :ad
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :correct_user,only: [:edit, :update, :destroy]
  # GET /ads or /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1 or /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    #@ad = Ad.new
    @ad = current_user.ad.build

  end

  def myAd
    @ads = Ad.all
  end
  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    #@ad = Ad.new(ad_params)
    @ad = current_user.ad.build(ad_params)
    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ad = current_user.ad.find_by(id: params[:id])
    redirect_to ad_path,notice: "Not Authorised to Edit" if @ad.nil?
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:name, :email, :phone, :description, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description,class:"form-control",rows:"3" %>
  </div>

 <div class="field form-group">

    <%= form.number_field :user_id,id: :ad_user_id,class:"form-control",type: :hidden,value:current_user.id %>
  </div>


  
  <div class="actions form-group">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Edit Advertisement</h1>

<%= render 'form', ad: @ad %>
 
<%= link_to 'Back', myAd_path,class:'btn btn-info' %>

app/views/ads/index.html.erb
 <% if user_signed_in? %>
<% @ads.each do |ad| %>
<div class="jumbotron">

  <h1 class="display-4"><%= ad.description %></h1>
  <h4>Name : <%= ad.name %></h4>
  <hr class="my-4">
  <p>Email : <%= ad.email %> | Phone : <%= ad.phone %></p>
 
  <div class="form-inline">
  <div class="form-group mx-sm-3">
    <input type="text" class="form-control"  placeholder="Add Comment">
  </div>
  <button class="btn btn-primary" href="#" role="button">send</button>
</div>
</div>
<% end %>
<%= link_to 'New Ad', new_ad_path,class:"btn btn-info" %>
<% else %>

<h1>Welcome to the Advertisement App. Sign Up to Continue..

<% end %>

app/views/ads/myAd.html.erb
<% @ads.each do |ad| %>
<% if ad.user_id == current_user.id %>
<div class="jumbotron">

  <h1 class="display-4"><%= ad.description %></h1>
  <h4>Name : <%= ad.name %></h4>
  <hr class="my-4">
  <p>Email : <%= ad.email %> | Phone : <%= ad.phone %></p>
  <div class="form-inline">
    <%= link_to 'Edit', edit_ad_path(ad),class:"btn btn-primary mx-sm-3" %>
    <%= link_to 'Delete', ad,class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
</div>
 <% end  %>
<% end %>

app/views/ads/new.html.erb
<br>
<%= render 'form', ad: @ad %>

<%= link_to 'Back', ads_path,class:"btn btn-primary" %>

app/views/ads/show.html.erb
<div class="jumbotron">

  <h1 class="display-4"><%= @ad.description %></h1>
  <h4>Name : <%= @ad.name %></h4>
  <hr class="my-4">
  <p>Email : <%= @ad.email %> | Phone : <%= @ad.phone %></p>
 
  <%= link_to 'Edit', edit_ad_path(@ad),class:'btn btn-info' %>      
  <%= link_to 'Back', ads_path,class:'btn btn-info' %>
 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Advertisement App',root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Make New Ad',new_ad_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Ads',myAd_path,class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Out',destroy_user_session_path,method: :delete,class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile',edit_user_registration_path,class:"nav-link" %>
        </li>

        <% else %>
          <li class="nav-item">
          <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Log In',new_user_session_path,class:"nav-link" %>
        </li>

        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <title>Advertisement App</title>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
    <br/>
    </div>
  </body>
</html>